In [1]:
import numpy as np

In [2]:

def rnn_cell_forward(xt, a_prev, parameters):
    
    # Retrieve parameters from "parameters"
    Wax = parameters["Wax"]
    Waa = parameters["Waa"]
    Wya = parameters["Wya"]
    ba = parameters["ba"]
    by = parameters["by"]
    
    def softmax(x):
        e_x = np.exp(x - np.max(x))
        return e_x / e_x.sum(axis=0)
    
    # compute next activation state using the formula given above
    a_next = np.tanh(np.dot(Waa,a_prev)+np.dot(Wax,xt)+ba)
    # compute output of the current cell using the formula given above
    yt_pred = softmax(np.dot(Wya,a_next) + by)
    
    # store values you need for backward propagation in cache
    cache = (a_next, a_prev, xt, parameters)
    
    return a_next, yt_pred, cache

In [3]:
np.random.seed(1)
xt_tmp = np.random.randn(3,10)
a_prev_tmp = np.random.randn(5,10)
parameters_tmp = {}
parameters_tmp['Waa'] = np.random.randn(5,5)
parameters_tmp['Wax'] = np.random.randn(5,3)
parameters_tmp['Wya'] = np.random.randn(2,5)
parameters_tmp['ba'] = np.random.randn(5,1)
parameters_tmp['by'] = np.random.randn(2,1)

a_next_tmp, yt_pred_tmp, cache_tmp = rnn_cell_forward(xt_tmp, a_prev_tmp, parameters_tmp)
print("a_next[4] = \n", a_next_tmp[4])
print("a_next.shape = \n", a_next_tmp.shape)
print("yt_pred[1] =\n", yt_pred_tmp[1])
print("yt_pred.shape = \n", yt_pred_tmp.shape)

a_next[4] = 
 [ 0.59584544  0.18141802  0.61311866  0.99808218  0.85016201  0.99980978
 -0.18887155  0.99815551  0.6531151   0.82872037]
a_next.shape = 
 (5, 10)
yt_pred[1] =
 [0.9888161  0.01682021 0.21140899 0.36817467 0.98988387 0.88945212
 0.36920224 0.9966312  0.9982559  0.17746526]
yt_pred.shape = 
 (2, 10)


In [4]:
xt_tmp

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
        -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
        -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
        -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547]])

In [5]:


def rnn_forward(x, a0, parameters):
    
    # Initialize "caches" which will contain the list of all caches
    caches = []
    
    # Retrieve dimensions from shapes of x and parameters["Wya"]
    n_x, m, T_x = x.shape
    n_y, n_a = parameters["Wya"].shape
    
    # initialize "a" and "y_pred" with zeros (≈2 lines)
    a = np.zeros((n_a,m,T_x), dtype=float)
    y_pred = np.zeros((n_y,m,T_x), dtype=float)
    print(y_pred)
    print(y_pred.shape)
    # Initialize a_next (≈1 line)
    a_next = a0
    
    # loop over all time-steps of the input 'x' (1 line)
    for t in range(T_x):
        # Update next hidden state, compute the prediction, get the cache (≈2 lines)
        xt = x[:, :, t]
        a_next, yt_pred, cache= rnn_cell_forward(xt, a_next, parameters)
        a[:,:,t] = a_next
        # Save the value of the prediction in y (≈1 line)
        y_pred[:,:,t] = yt_pred
        print(y_pred[:,:,t])
        print("***************************************")
        # Append "cache" to "caches" (≈1 line)
        caches.append(cache)
        
    # store values needed for backward propagation in cache
    caches = (caches, x)
    print("Y_t pred shape  ",yt_pred.shape)
    return a, y_pred, caches

In [6]:
np.random.seed(1)
x_tmp = np.random.randn(3,10,4)
a0_tmp = np.random.randn(5,10)
parameters_tmp = {}
parameters_tmp['Waa'] = np.random.randn(5,5)
parameters_tmp['Wax'] = np.random.randn(5,3)
parameters_tmp['Wya'] = np.random.randn(2,5)
parameters_tmp['ba'] = np.random.randn(5,1)
parameters_tmp['by'] = np.random.randn(2,1)

a_tmp, y_pred_tmp, caches_tmp = rnn_forward(x_tmp, a0_tmp, parameters_tmp)
print("a[4][1] = \n", a_tmp[4][1])
print("a.shape = \n", a_tmp.shape)
print("y_pred[1][3] =\n", y_pred_tmp[1][3])
print("y_pred.shape = \n", y_pred_tmp.shape)
print("caches[1][1][3] =\n", caches_tmp[1][1][3])
print("len(caches) = \n", len(caches_tmp))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 10, 4)
[[9.99129368e-01 9.99394165e-01 9.94277463e-01 2.04396268e-01
  7.42084036e-01 3.43688280e-01 9.39252776e-01 9.35504646e-01
  6.39183022e-01 6.07750160e-01]
 [8.70631878e-04 6.05834882e-04 5.72253732e-03 7.95603732e-01
  2.57915964e-01 6.56311720e-01 6.07472236e-02 6.44953539e-02
  3.60816978e-01 3.92249840e-01]]
***************************************
[[0.89077259 0.32694781 0.99599937 0.13775139 0.41603066 0.99886751
  0.7075855  0.98573143 0.02350082 0.89866672]
 [0.10922741 0.67305219 0.00400063 0.86224861 0.58396934 0.00113249
  0.2924145  0.01426857 0.97649918 0.10133328]]
***************************************
[[7.04206315e-01 9.98789616e-01 9.97939

In [7]:
y_pred_tmp.shape

(2, 10, 4)

In [8]:
y_pred_tmp

array([[[9.99129368e-01, 8.90772592e-01, 7.04206315e-01, 9.19730000e-01],
        [9.99394165e-01, 3.26947813e-01, 9.98789616e-01, 9.88219303e-01],
        [9.94277463e-01, 9.95999371e-01, 9.97939529e-01, 2.76624090e-01],
        [2.04396268e-01, 1.37751394e-01, 8.88817431e-01, 1.84840534e-01],
        [7.42084036e-01, 4.16030656e-01, 5.96207274e-02, 9.56452021e-01],
        [3.43688280e-01, 9.98867515e-01, 9.89766361e-01, 8.99137589e-01],
        [9.39252776e-01, 7.07585502e-01, 8.85151052e-01, 3.34768716e-01],
        [9.35504646e-01, 9.85731426e-01, 9.37994449e-01, 6.45782938e-01],
        [6.39183022e-01, 2.35008185e-02, 8.20174082e-01, 3.42431253e-01],
        [6.07750160e-01, 8.98666718e-01, 9.99114486e-01, 9.90187623e-01]],

       [[8.70631878e-04, 1.09227408e-01, 2.95793685e-01, 8.02699998e-02],
        [6.05834882e-04, 6.73052187e-01, 1.21038427e-03, 1.17806974e-02],
        [5.72253732e-03, 4.00062909e-03, 2.06047094e-03, 7.23375910e-01],
        [7.95603732e-01, 8.62248606e

In [9]:
x_tmp

array([[[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
        [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
        [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071],
        [-0.3224172 , -0.38405435,  1.13376944, -1.09989127],
        [-0.17242821, -0.87785842,  0.04221375,  0.58281521],
        [-1.10061918,  1.14472371,  0.90159072,  0.50249434],
        [ 0.90085595, -0.68372786, -0.12289023, -0.93576943],
        [-0.26788808,  0.53035547, -0.69166075, -0.39675353],
        [-0.6871727 , -0.84520564, -0.67124613, -0.0126646 ],
        [-1.11731035,  0.2344157 ,  1.65980218,  0.74204416]],

       [[-0.19183555, -0.88762896, -0.74715829,  1.6924546 ],
        [ 0.05080775, -0.63699565,  0.19091548,  2.10025514],
        [ 0.12015895,  0.61720311,  0.30017032, -0.35224985],
        [-1.1425182 , -0.34934272, -0.20889423,  0.58662319],
        [ 0.83898341,  0.93110208,  0.28558733,  0.88514116],
        [-0.75439794,  1.25286816,  0.51292982, -0.29809284],
      

In [10]:
a0_tmp

array([[-0.02461696, -0.77516162,  1.27375593,  1.96710175, -1.85798186,
         1.23616403,  1.62765075,  0.3380117 , -1.19926803,  0.86334532],
       [-0.1809203 , -0.60392063, -1.23005814,  0.5505375 ,  0.79280687,
        -0.62353073,  0.52057634, -1.14434139,  0.80186103,  0.0465673 ],
       [-0.18656977, -0.10174587,  0.86888616,  0.75041164,  0.52946532,
         0.13770121,  0.07782113,  0.61838026,  0.23249456,  0.68255141],
       [-0.31011677, -2.43483776,  1.0388246 ,  2.18697965,  0.44136444,
        -0.10015523, -0.13644474, -0.11905419,  0.01740941, -1.12201873],
       [-0.51709446, -0.99702683,  0.24879916, -0.29664115,  0.49521132,
        -0.17470316,  0.98633519,  0.2135339 ,  2.19069973, -1.89636092]])

In [11]:
a0_tmp.shape

(5, 10)